dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('main-dashboard/', views.main_dashboard, name='main-dashboard'),
    path('add-data/', views.addData, name='add-data')
]

gisportal/urls.py
from django.urls import path 
from .  import views
from gisportal.views import CesiumIonAssetView, CesiumIonToken 


app_name = 'gisportal'

urlpatterns=[
    
    path('api/cesium-ion-token/',CesiumIonToken.as_view(), name="get-cesium-token"),
    
    path('api/metadata/<int:object_id>/', views.get_metadata, name='get_metadata'),
    
    path('dranef/',views.DRANEFList.as_view(),name="dranef"),
    path('dranef/<int:pk>/',views.DRANEFDetailView.as_view(), name="dranef-details"),
    
    path('dpanef/', views.DPANEFList.as_view(),name="dpanef-list"),
    path('dpanef/<int:pk>/', views.DPANEFDetailView.as_view(),name="dpanef-details"),
    
    path('zdtf/', views.ZDTFList.as_view(),name="zdtf-list"),
    path('zdtf/<int:pk>/', views.ZDTFDetailView.as_view(),name="zdtf-details"),
    
    path('dfp/', views.DFPList.as_view(),name="dfp-list"),
    path('dfp/<int:pk>/', views.DFPDetailView.as_view(),name="dfp-Details"),
    
    path('regions/', views.RegionList.as_view(),name="region-list"),
    path('regions/<int:pk>/', views.RegionDetailView.as_view(),name="region-Details"),
    
    path('province/', views.ProvinceList.as_view(),name="province-list"),
    path('province/<int:pk>/', views.ProvinceDetailView.as_view(),name="province-Details"),
    
    path('commune/', views.CommuneList.as_view(),name="commune-list"),
    path('commune/<int:pk>/', views.CommuneDetailView.as_view(),name="commune-Details"),
    
    path('forest/', views.ForestList.as_view(), name="forest-list"),
    path('forest/<int:pk>/', views.ForestDetailView.as_view(), name="forest-Details"),

    path('canton/', views.CantonList.as_view(), name="canton-list"),
    path('canton/<int:pk>/', views.CantonDetailView.as_view(), name="canton-Details"),
    
    path('groupe/', views.GroupeList.as_view(), name="groupe-list"),
    path('groupe/<int:pk>/', views.GroupeDetailView.as_view(), name="groupe-Details"),
    
    path('parcelle/', views.ParcelleList.as_view(), name="parcelle-list"),
    path('parcelle/<int:pk>/', views.ParcelleDetailView.as_view(), name="parcelle-Details"),
    
    path('species/', views.SpeciesList.as_view(), name="species-list"),
    path('species/<int:pk>/', views.SpeciesDetailView.as_view(), name="species-Details"),
    
    path('parcelspecies/', views.ParcelSpeciesList.as_view(), name="parcelspecies-list"),
    path('parcelspecies/<int:pk>/', views.ParcelSpeciesDetailView.as_view(), name="parcelspecies-Details"),
    
   
    path('gisportal/', views.cesium_view, name='gisportal'),
    
    path('home/', views.home, name='home'),
    path('main-portal/',views.portal, name="portal"),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('about_us/', views.about_us, name='about_us'),
    path('signup/',views.signup, name='signup'),
    path('login/', views.login_view, name='authenticate/login'),
    
    path('cesium-ion/', CesiumIonAssetView.as_view(), name='cesium-ion-asset')
    
]

globegeoportal/urls.py
from django.contrib import admin 
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('globetudes/',include('globeportal.urls', namespace='globeportal')),
    path('auth_custom/',include('django.contrib.auth.urls')),
    path('dashboard/',include('dashboard.urls', namespace='dashboard')),
    path('auth_custom/',include('auth_custom.urls', namespace='auth_custom')),
]
admin.site.site_header= "Globetudes Geoportal Admin"
admin.site.index_title = "Geoportal Admin Site"

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render

# Create your views here.
def main_dashboard(request):
    return render(request, 'dashboard/main-dashboard.html')  # Specify the full path to the template

def addData(request):
    return render(request, 'dashboard/add-data.html')  # Specify the full path to the template

dashboard/templates/dashboard/add-data.html
{% extends 'dashboard/base_dashboard.html' %}

{% load static %}
<title>{% block title %}Geoportal Dashboard{% endblock title %}</title>

{% block extra_heads %}
<style>
   
</style>
{% endblock extra_heads %}

{% block content%}
    <div class="main">
        <div class="container">
            <h1>Add Data</h1>
            <select class="form-select" aria-label="Default select example">
                <option selected>Open this select menu</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
            </select>
        </div>
        <br/>
        <div class="container" style="display: flex; flex:1; flex-direction: row; justify-content: space-between;">
            
            <div style="flex:0.5; padding: 20px !important;">
                <div class="mb-12" style="margin-bottom: 10px;">
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                  </div>

                  <div class="mb-12" style="margin-bottom: 10px;">
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                  </div>

                  <button type="button" class="btn btn-primary">Primary</button>

            </div>
            <div style="flex:0.5; padding: 20px !important;">
                <div class="input-group mb-12">
                <label class="input-group-text" for="inputGroupFile01">Upload</label>
                <input type="file" class="form-control" id="inputGroupFile01">
                </div>
            </div>
        </div>
    </div>
{% endblock content%}

{% block extra_scripts %}
        
{% endblock extra_scripts %}
</body>
</html>

dashboard/templates/dashboard/base_dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Geoportal Dashboard{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/dashboard_style.css' %}">
    {% block extra_heads %}
    {% endblock extra_heads %}
</head>
<body>
    <div class="container-fluid">
        <!-- Topbar -->
        <div class="topbar">
            <div class="logo">
                <img src="{% static 'img/globetudes.jpg' %}" alt="Logo">
            </div>
            <div class="search"></div>

            <!-- User Profile Dropdown -->
            <div class="profile-dropdown">
                <span class="dropdown-toggle">Welcome, <strong>{{ user.username }}</strong></span>
                <div class="dropdown-content">
                    <a href="#"><i class="fas fa-user"></i> Profile</a>
                    <a href="#"><i class="fas fa-cog"></i> Settings</a>
                    <a href="#"><i class="fas fa-sign-out-alt"></i> Logout</a>
                </div>
            </div>

            <!-- User Avatar -->
            <div class="user">
                <img src="{{ user.profile.photo.url }}" alt="User" oncontextmenu="return false;" style="pointer-events: none;">
            </div>
        </div>

        <!-- Sidebar -->
        <div class="sidebar">
            <ul>
                <li>
                    <a href="{% url 'dashboard:main-dashboard' %}">
                        <i class="fa fa-th-large"></i>
                        <div>Dashboard</div>
                    </a>
                </li>
                <li>
                    <a href="{% url 'globeportal:home' %}">
                        <i class="fa-solid fa-eye"></i>
                        <div>Visualize</div>
                    </a>
                </li>
                <li>
                    <a href="{% url 'dashboard:add-data' %}">
                        <i class="fa-sharp fa-solid fa-plus"></i>
                        <div>Add Data</div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa-solid fa-chart-bar"></i>
                        <div>Analytics</div>
                    </a>
                </li>
                <li>
                    <a href="http://127.0.0.1:9008/admin/">
                        <i class="fa-solid fa-gear"></i>
                        <div>Settings</div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa-regular fa-question"></i>
                        <div>Help</div>
                    </a>
                </li>
            </ul>
        </div>

        <!-- Main Content -->
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="{% static 'js/dashboard_chart1.js' %}"></script>
    <script src="{% static 'js/dashboard-chart2.js' %}"></script>
    
    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

dashboard/templates/dashboard/main-dashboard.html
{% extends 'dashboard/base_dashboard.html' %}

{% load static %}


<title>{% block title %}🌍 Globeportal {% endblock title %}</title>

{% block extra_heads %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
{% endblock extra_heads %}

{% block content %}
<div class="main">
    <!-- Cards Section -->
    <div class="cards">
        <a href="{% url 'globeportal:home' %}" target="_blank">
            <div class="card">
                <div class="card-content">
                    <div class="number"></div>
                    <div class="card-name">Visualize</div>
                </div>
                <div class="icon-box">
                    <img src="https://cdn-icons-png.flaticon.com/512/1700/1700483.png" alt="Visualize-icon">
                </div>
            </div>
        </a>

        <a href="{% url 'dashboard:add-data' %}" >
            <div class="card">
                <div class="card-content">
                    <div class="number"></div>
                    <div class="card-name">Add Data</div>
                </div>
                <div class="icon-box">
                    <img src="https://cdn-icons-png.flaticon.com/512/2312/2312340.png" alt="Add Data-icon">
                </div>
            </div>
        </a>

        <a href="#">
            <div class="card">
                <div class="card-content">
                    <div class="number"></div>
                    <div class="card-name">Users</div>
                </div>
                <div class="icon-box">
                    <img src="https://www.iconpacks.net/icons/1/free-user-group-icon-296-thumb.png" alt="Users-icon">
                </div>
            </div>
        </a>

        <div class="card">
            <div class="card-content">
                <div class="number"></div>
                <div class="card-name">Settings</div>
            </div>  
            <div class="icon-box">
                <img src="https://www.iconpacks.net/icons/1/free-settings-icon-778-thumb.png" alt="Settings-icon">
            </div>
        </div>
    </div>

    <!-- Charts Section -->
    <div class="charts">
        {% comment %} <h2>Forest Graphics</h2> {% endcomment %}
        
        <div class="chart">
            <div class="chartType">
                <button onclick="setChartType('bar')" >Bar charts</button>
                <button onclick="setChartType('line')">Line chart</button>
                <button onclick="setChartType('pie')">Pie chart</button>
                <h4 id="graphtitle">Forest Graphics Details </h4>

            </div>
            
            <select id="graphcsAttr">
                <option value="dog">Superficie des Forets (km²)</option>
                <option value="dog">Especes des Forets (%)</option>
              </select>
            <button id="itemDetails" >See Details</button>
                
            
            <canvas id="lineChart"></canvas>
        </div>
    </div>
</div>
{% endblock content %}

{% block extra_scripts %}
<!-- Additional scripts can go here -->
{% endblock extra_scripts %}